pub const LIFETIME: u16 = 1;
pub const TIMEOUT: u64 = 6;
pub const CONTEXT_LENGTH: usize = 32;
pub const THREADS: usize = 10000;
pub const BATCH_SIZE: usize = 100;
pub const MAX_REDIRECTS: usize = 8;
pub const API_KEY: &str = "f6L3xYuZALbYwzZE242j58c4tZc7B9t3FB5RfwbVYCKWdkstGsdjz88wbGCxw8Nt";
// pub const API_URL: &str = "https://forager.jeremyjacob.dev/api/";
pub const API_URL: &str = "http://localhost:3000/api/";