name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TARGET: x86_64-unknown-linux-musl
  CARGO_TERM_COLOR: always
  CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER: arm-linux-gnueabihf-ld

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Binutils
      run: sudo apt install binutils-arm-linux-gnueabihf
    - name: Install pkg-config
      run: sudo apt install pkg-config
    - name: Install Nightly
      run: rustup install nightly
    - name: Default Nightly
      run: rustup default nightly
    - name: Add Target
      run: rustup target add $TARGET
    - name: Build
      working-directory: ./worker
      run: cargo build --verbose -r --target $TARGET
    - name: Log
      run: tree .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "worker/target/release/forager"
        name: Worker Binary
        tag: ${{ github.run_id }}
        token: ${{ secrets.GITHUB_TOKEN }}
